services:
    postgres:
            container_name: void0-postgres
            image: postgres:latest
            restart: unless-stopped
            environment:
                - POSTGRES_USER=void0
                - POSTGRES_PASSWORD=Please-change-password
                - POSTGRES_DB=void0
            ports:
                - 5432:5432
            volumes:
                - postgres_data:/var/lib/postgresql/data
    
volumes:
    postgres_data:
    
networks:
    default: {}